
doc.css:
	wget https://raw.githubusercontent.com/keplerproject/kepler/master/css/doc.css

check:
	xmllint --noout --valid coat.html
	xmllint --noout --valid index.html
	xmllint --noout --valid inject.html
	xmllint --noout --valid memoize.html
	xmllint --noout --valid meta_class.html
	xmllint --noout --valid meta_role.html
	xmllint --noout --valid mock.html
	xmllint --noout --valid role.html
	xmllint --noout --valid types.html
	xmllint --noout --valid uml.html

