#! /usr/bin/lua
--
-- lua-Coat : <http://lua-coat.luaforge.net/>
--

if #arg == 0 then
    print "Usage: coat2dot [--no-attr] [--no-meth] [--no-meta] module1 [module2, ...]"
    os.exit(0)
end

local m = require 'Coat.UML'

local opt = {}
for _, v in ipairs(arg) do
    if v:sub(1,2) == '--' then
        local k = v:sub(3):gsub('-','_')
        opt[k] = true
    else
        require(v)
    end
end

print(m.to_dot(opt))

--
-- Copyright (c) 2009-2010 Francois Perrad
--
-- This program is licensed under the terms of the MIT/X11 license,
-- like Lua itself.
--
